databases:
  - name: helihire
    databaseName: helihiredb
    user: helihireuser

services:
  - type: web
    name: heli-hire-capstone-backend
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helihire
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false