default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: ismail
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: heli_hire_captone_backend_development
  username: postgres
test:
  <<: *default
  database: heli_hire_captone_backend_test
  username: postgres
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
